"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "ronit gandhi"
email = "ronitgandhi96@gmail.com"

[ui]
default-command = ["log", "-r", "::"]
editor = "nvim"
diff-editor = ":builtin"

revsets.immutable-heads = "none()"

[aliases]
la = ["log", "-r", "::", "--color=always", "--template", 'commit_id.short() ++ " " ++ description.first_line()']
gf = ["git", "fetch"]
bc = ["bookmark", "create"]

